### ISSUE TITLE
运行danmu.py时出现AttributeError

### ISSUE THREAD

**Issue by luobolong** [archibate/qdanmu#1]
在Linux环境下，尝试运行danmu.py时遇到一个AttributeError。

报错信息：

```
当前版本：32caf36a
Traceback (most recent call last):
File "/home/ben/Workspace/PythonWorkspace/qdanmu/danmu.py", line 936, in <module>
sys.exit(main())
File "/home/ben/Workspace/PythonWorkspace/qdanmu/danmu.py", line 929, in main
win = MainWindow()
File "/home/ben/Workspace/PythonWorkspace/qdanmu/danmu.py", line 751, in init
self.setAttribute(Qt.WA_NoSystemBackground, True)
AttributeError: 'MainWindow' object has no attribute 'setAttribute'. Did you mean: 'testAttribute'?
```

 - Python版本：Python 3.11.8
 - 相关软件包版本：

```
Package            Version
------------------ ------------
certifi            2024.2.2
charset-normalizer 3.3.2
idna               3.6
pillow             10.2.0
pip                24.0
pypng              0.20220715.0
PySide2            5.13.2
qrcode             7.4.2
requests           2.31.0
setuptools         65.5.0
shiboken2          5.13.2
typing_extensions  4.10.0
urllib3            2.2.1
```

应该是版本不兼容所导致的问题，希望能够提供Python环境的版本信息，并在requirements.txt中指定具体软件包的版本号。

**Comment by luobolong** [comment]
我使用python3.9版本成功构建，但似乎在wayland环境下弹幕助手无法正常工作
